// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { VLifeContextProvider } from "@/store/context";
import { headers } from "next/headers";
import { checkAuth } from "@/lib/checkAuth";
// import Layout from "@/layout/Layout";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headerStore = await headers();

  // 🔥 Always gives correct route path
  const pathname = headerStore.get("x-matched-path") || "/";

  const result = await checkAuth(pathname);

  if (result instanceof Response) {
    return result; // redirect if unauthorized
  }

  // Everything allowed → render UI layout
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <VLifeContextProvider>
          <Toaster position="top-right" richColors closeButton />
          {children}
        </VLifeContextProvider>
      </body>
    </html>
  );
}
