import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { VLifeContextProvider } from "@/store/context";
import { checkAuth } from "@/lib/checkAuth";
import Layout from "@/layout/Layout";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headerStore = await headers();
  const pathname = headerStore.get("x-matched-path") || "/";

  const redirectPath = await checkAuth(pathname);

  if (redirectPath) redirect(redirectPath);

  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <VLifeContextProvider>
          <Toaster position="top-right" richColors closeButton />
          {children}
        </VLifeContextProvider>
      </body>
    </html>
  );
}
